//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos
    {
        public Archivos()
        {
            this.Historiales = new HashSet<Historiales>();
        }
    
        public long PkID_Archivo { get; set; }
        public int FkID_Carrera { get; set; }
        public string Autor { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
        public string Ruta { get; set; }
        public bool Estado { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual ICollection<Historiales> Historiales { get; set; }
    }
}
