//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envios
    {
        public int PkID_Envio { get; set; }
        public long FkID_Archivo { get; set; }
        public int FkID_Usuario { get; set; }
        public string Nombre_Receptor { get; set; }
        public string Identidad_Receptor { get; set; }
        public string Correo_Receptor { get; set; }
        public System.DateTime Fecha_Envio { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
