//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_bibliotecahEntities : DbContext
    {
        public admin_bibliotecahEntities()
            : base("name=admin_bibliotecahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archivos> Archivos { get; set; }
        public DbSet<Carreras> Carreras { get; set; }
        public DbSet<Configuraciones> Configuraciones { get; set; }
        public DbSet<Envios> Envios { get; set; }
        public DbSet<Historiales> Historiales { get; set; }
        public DbSet<Operaciones> Operaciones { get; set; }
        public DbSet<TiposCarreras> TiposCarreras { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
