//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public Operaciones()
        {
            this.Historiales = new HashSet<Historiales>();
        }
    
        public int PkID_Operacion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Historiales> Historiales { get; set; }
    }
}
