//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Envios = new HashSet<Envios>();
            this.Historiales = new HashSet<Historiales>();
        }
    
        public int PkID_Usuario { get; set; }
        public string Login_Name { get; set; }
        public string Nombre_Completo { get; set; }
        public string Password { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public bool Administrador { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Envios> Envios { get; set; }
        public virtual ICollection<Historiales> Historiales { get; set; }
    }
}
